<a href="https://colab.research.google.com/github/iyline-sigey/PREDICTIVE-ANALYSIS-ON-REMOTE-LEARNING/blob/Modelling/MLPClassifier%26NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
#for metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense, Dropout, SpatialDropout1D
from tensorflow.keras.layers import Embedding

from sklearn.neural_network import MLPClassifier

from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df_clean = pd.read_csv('/content/modeling_data.csv')

### Neural Networks MLP

In [3]:
#Declaring our X and Y variables
X = df_clean.clean_tweet.values
y = df_clean['class'].values

In [4]:
# Train Test Split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=10)

In [5]:
# set a vocabulary size. This is the maximum number of words that can be used.
vocabulary_size = 10000

# create the tokenizer that comes with Keras.
tokenizer = Tokenizer(num_words=vocabulary_size)
tokenizer.fit_on_texts(X_train)

# convert the texts to sequences.
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_test)

In [6]:
max_words = 5000
max_len = 5000

X_train_seq_padded = pad_sequences(X_train_seq, maxlen=200)
X_val_seq_padded  = pad_sequences(X_val_seq, maxlen=200)

In [7]:
#creating an instamce ofthe model
mlp = MLPClassifier(hidden_layer_sizes = (13, 13,13), max_iter = 500)

# fitting the data
mlp.fit(X_train_seq_padded,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [8]:
# Now that we have our model in place, let's do the prediction
from sklearn import metrics
pred = mlp.predict(X_val_seq_padded)

mlp_nn = metrics.accuracy_score(pred,y_test)*100

# Evaluating the performance of ur model

print('The accuracy of the model is ',metrics.accuracy_score(y_test, pred))

print (confusion_matrix(y_test,pred))

print('-----------------------------------------------')

print(classification_report(y_test,pred))

The accuracy of the model is  0.6290322580645161
[[11 11]
 [12 28]]
-----------------------------------------------
              precision    recall  f1-score   support

           0       0.48      0.50      0.49        22
           1       0.72      0.70      0.71        40

    accuracy                           0.63        62
   macro avg       0.60      0.60      0.60        62
weighted avg       0.63      0.63      0.63        62



In [9]:
# Extracting the weights and bias vectors

# Checking the number of weights 
len(mlp.coefs_) 

# Checking the number of biases 
len(mlp.intercepts_)

4

Naive bayes

In [13]:
#Declaring our X and Y variables
X = df_clean.clean_tweet.values
y = df_clean['class'].values

In [14]:
# Train Test Split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=10)

In [15]:
# set a vocabulary size. This is the maximum number of words that can be used.
vocabulary_size = 10000

# create the tokenizer that comes with Keras.
tokenizer = Tokenizer(num_words=vocabulary_size)
tokenizer.fit_on_texts(X_train)

# convert the texts to sequences.
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_test)

In [16]:
max_words = 5000
max_len = 5000

X_train_seq_padded = pad_sequences(X_train_seq, maxlen=200)
X_val_seq_padded  = pad_sequences(X_val_seq, maxlen=200)

In [19]:
# Training the Model
# We will start by splitting our data into training and test sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Fitting our model 
# Then, all that we have to do is initialize the Naive Bayes Classifier and fit the data. 
# For text classification problems, the Multinomial Naive Bayes Classifier is well-suited
# 
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train_seq_padded, y_train)

# Evaluating the Model
# Once we have put together our classifier, we can evaluate its performance in the testing set
# 
predicted = model.predict(X_val_seq_padded)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))
print(classification_report(y_test, predicted))

0.532258064516129
[[14  9]
 [20 19]]
              precision    recall  f1-score   support

           0       0.41      0.61      0.49        23
           1       0.68      0.49      0.57        39

    accuracy                           0.53        62
   macro avg       0.55      0.55      0.53        62
weighted avg       0.58      0.53      0.54        62



In [21]:
# Training our model and printing out metrics
# 
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()  
model = clf.fit(X_train_seq_padded, y_train) 
predicted = model.predict(X_val_seq_padded)
print(np.mean(predicted == y_test))
print(confusion_matrix(y_test, predicted))
print(classification_report(y_test, predicted))

0.3548387096774194
[[21  2]
 [38  1]]
              precision    recall  f1-score   support

           0       0.36      0.91      0.51        23
           1       0.33      0.03      0.05        39

    accuracy                           0.35        62
   macro avg       0.34      0.47      0.28        62
weighted avg       0.34      0.35      0.22        62

